AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an ECS Service from the ECS Console.
Parameters:
  ECSClusterName:
    Type: String
    Default: MyEcsCluster
  SecurityGroupIDs:
    Type: CommaDelimitedList
    Default: sg-018c9a1939250f04c
  SubnetIDs:
    Type: CommaDelimitedList
    Default: 'subnet-09c6ed811b640a00a,subnet-08b71250690c46411,subnet-0a6eec9bb13d7854a'
  VpcID:
    Type: String
    Default: vpc-0cd358837598ca1ec
  LoadBalancerName:
    Type: String
    Default: ''
Resources:
  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: MyEcsCluster
      TaskDefinition: 'arn:aws:ecs:ap-south-1:769796820311:task-definition/nginxdemos-hello:3'
      LaunchType: FARGATE
      ServiceName: nginx-service
      SchedulingStrategy: REPLICA
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIDs
          Subnets: !Ref SubnetIDs
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      Tags: []
      EnableECSManagedTags: true
  AutoScalingTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MaxCapacity: '3'
      MinCapacity: '1'
      ResourceId: service/MyEcsCluster/nginx-service
      RoleARN: >-
        arn:aws:iam::769796820311:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
    DependsOn:
      - ECSService
  AutoScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: Test-policy
      PolicyType: TargetTrackingScaling
      ResourceId: service/MyEcsCluster/nginx-service
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        DisableScaleIn: false
        TargetValue: '1'
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
Outputs:
  ClusterName:
    Description: The cluster used to create the service.
    Value: !Ref ECSClusterName
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
  AutoScalingTarget:
    Value: !Ref AutoScalingTarget
  AutoScalingPolicy:
    Value: !Ref AutoScalingPolicy
